services:
  - type: web
    name: metabase
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        sync: false
      - key: MB_DB_PORT
        sync: false
      - key: MB_DB_USER
        sync: false
      - key: MB_DB_PASS
        sync: false
      - key: MB_DB_HOST
        sync: false
