services:
  - type: web
    name: metabase
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: PORT
        value: "10000"
    port: 10000
    scaling:
      minInstances: 1
      maxInstances: 1
